---
title: "HPHI Loss Ratios"
author: "Christopher Boutte"
date: "March 24, 2017"
output:
  html_document: 
      css: mystyle.css
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(RODBC)
library(stringr)
library(lubridate)
library(knitr)

```



```{r Query and Cleaning, echo=FALSE, include=FALSE}

HPHI_Policy_Data <- read_csv("HPHI_Raw_Data.csv")
ITD_Claims_Data <- read_csv("ITD_Claims.csv")
ITD_Premiums_Data <- read_csv("ITD_Premiums.csv")

ITD_Claims_Data2 <- select(ITD_Claims_Data, PPOLICY, CLAM0701)
ITD_Premiums_Data2 <- select(ITD_Premiums_Data, PPOLICY, PHPAMT101)

## Filter out duplicates

HPHI_Policy_Data2 <- HPHI_Policy_Data %>%
  group_by(PPOLICY, PCOMPANY, PBLOCK, PRIDER, PSTATUS, PFORM, PPLAN, PISSUEDT, PISSUEST, PSNO13, PSCD09, AGCD01, AGENTNO, AGNAMEF, 
           AGNAMEL, AGTOPNAMEL) %>%
  count() 

HPHI_Policy_Data3 <- HPHI_Policy_Data2 %>%
  group_by(PPOLICY) %>%
  mutate(rank = min_rank(desc(AGCD01))) %>%
  filter(rank == 1) %>%
  mutate(rank2 = min_rank(AGENTNO)) %>%
  filter(rank2 == 1)

## Join in claims and premiums, create date columns, fix agent names, and select needed columns

HPHI_Policy_Data3$PISSUEDT <- ymd(HPHI_Policy_Data3$PISSUEDT)

HPHI_Policy_Data3$AGTOPNAMEL <- sub("BENEFITS TECH DIVISION 4", "BENEFITS TECH DIVISION", HPHI_Policy_Data3$AGTOPNAMEL)
HPHI_Policy_Data3$AGTOPNAMEL <- sub("MATTHEW MCKINNEY LLC-2", "MCKINNEY", HPHI_Policy_Data3$AGTOPNAMEL)

HPHI_Full_Data <- HPHI_Policy_Data3 %>%
  left_join(ITD_Premiums_Data2, by = "PPOLICY") %>%
  left_join(ITD_Claims_Data2, by = "PPOLICY") %>%
  mutate(Iss_Year = year(PISSUEDT)) %>%
  select(-PRIDER, -n, -rank, -rank2) %>%
  mutate(PHPAMT101 = if_else(is.na(PHPAMT101), 0, PHPAMT101), CLAM0701 = if_else(is.na(CLAM0701), 0, CLAM0701),
         LR = round((CLAM0701 / PHPAMT101) * 100), digits = 0)

HPHI_Full_Data2 <- HPHI_Full_Data %>%
  select(-digits) %>%
  mutate(Writing_Agent = paste(AGNAMEF, AGNAMEL, sep = ", ")) %>%
  mutate(LR = if_else(is.nan(LR), 0, LR))

## Summary Tables by various variables

LR_By_Issue_State <- HPHI_Full_Data2 %>%
  group_by(PISSUEST) %>%
  summarise(Premiums_Sum = sum(PHPAMT101), Claims_Sum = sum(CLAM0701), Policy_Count = n()) %>%
  mutate(LR = round((Claims_Sum / Premiums_Sum * 100), digits = 0)) %>%
  filter(Premiums_Sum > 100000)

LR_By_Agent <- HPHI_Full_Data2 %>%
  group_by(Writing_Agent) %>%
  summarise(Premiums_Sum = sum(PHPAMT101), Claims_Sum = sum(CLAM0701), Policy_Count = n()) %>%
  mutate(LR = round((Claims_Sum / Premiums_Sum * 100), digits = 0))

LR_By_Agent_Top_Ten <- LR_By_Agent %>%
  arrange(desc(Policy_Count)) %>%
  head(n = 10)

LR_By_Issue_Year <- HPHI_Full_Data2 %>%
  group_by(Iss_Year) %>%
  summarise(Premiums_Sum = sum(PHPAMT101), Claims_Sum = sum(CLAM0701), Policy_Count = n()) %>%
  mutate(LR = round((Claims_Sum / Premiums_Sum * 100), digits = 0))

LR_By_Top_Agent <- HPHI_Full_Data2 %>%
  group_by(AGTOPNAMEL) %>%
  summarise(Premiums_Sum = sum(PHPAMT101), Claims_Sum = sum(CLAM0701), Policy_Count = n()) %>%
  mutate(LR = round((Claims_Sum / Premiums_Sum * 100), digits = 0)) %>%
  filter(Premiums_Sum > 1000, LR > 0, AGTOPNAMEL != "NA")

LR_By_Gender <- HPHI_Full_Data2 %>%
  group_by(PSCD09) %>%
  summarise(Premiums_Sum = sum(PHPAMT101), Claims_Sum = sum(CLAM0701), Policy_Count = n()) %>%
  mutate(LR = round((Claims_Sum / Premiums_Sum * 100), digits = 0)) %>%
  filter(PSCD09 != "NA")

LR_By_Issue_Age <- HPHI_Full_Data2 %>%
  group_by(PSNO13) %>%
  summarise(Premiums_Sum = sum(PHPAMT101), Claims_Sum = sum(CLAM0701), Policy_Count = n()) %>%
  mutate(LR = round((Claims_Sum / Premiums_Sum * 100), digits = 0)) %>%
  filter(PSNO13 != "NA", PSNO13 > 17, Policy_Count > 20)

LR_By_Issue_Age_Gender <- HPHI_Full_Data2 %>%
  group_by(PSNO13, PSCD09) %>%
  summarise(Premiums_Sum = sum(PHPAMT101), Claims_Sum = sum(CLAM0701), Policy_Count = n()) %>%
  mutate(LR = round((Claims_Sum / Premiums_Sum * 100), digits = 0)) %>%
  filter(PSNO13 != "NA", PSNO13 > 17, PSCD09 != "NA")



```

----

***

```{r ITD LR by Issue Age & Gender, echo=FALSE, message = FALSE}
LR_By_Issue_Age_Gender %>%
  filter(LR < 150, Policy_Count > 20) %>%
  ggplot(aes(x = PSNO13, y = LR, col = PSCD09)) +
  geom_line() +
  geom_point(aes(size = Policy_Count), alpha = .5) +
  geom_smooth(se = FALSE) +
  labs(title = "ITD LR by Issue Age & Gender", x = "Issue Age", size = "Policy Count", col = "Gender")
```

#####Comments

***

```{r ITD LR by Issue Age & Gender Facet, echo=FALSE, message = FALSE}
LR_By_Issue_Age_Gender %>%
  filter(LR < 150, Policy_Count > 20) %>%
  ggplot(aes(x = PSNO13, y = LR)) +
  geom_line(col = "blue") +
  geom_point(aes(size = Policy_Count), alpha = .5, col = "blue") +
  geom_smooth(se = FALSE, col = "red") +
  facet_wrap(~ PSCD09) +
  scale_x_continuous(breaks = c(20, 30, 40, 50, 60, 70)) +
  labs(title = "ITD LR by Issue Age & Gender", x = "Issue Age", size = "Policy Count")
```

#####Comments


***

```{r ITD LR by Issue Age & Gender, echo=FALSE, message = FALSE}
LR_By_Issue_Age_Gender %>%
  filter(LR < 150, Policy_Count > 20) %>%
  ggplot(aes(x = PSNO13, y = LR, col = PSCD09)) +
  geom_line() +
  geom_point(aes(size = Policy_Count), alpha = .5) +
  geom_smooth(se = FALSE) +
  labs(title = "ITD LR by Issue Age & Gender", x = "Issue Age", size = "Policy Count", col = "Gender")
```

#####Comments

***

```{r ITD LR by Issue Age & Gender Facet, echo=FALSE, message = FALSE}
LR_By_Issue_Age_Gender %>%
  filter(LR < 150, Policy_Count > 20) %>%
  ggplot(aes(x = PSNO13, y = LR)) +
  geom_line(col = "blue") +
  geom_point(aes(size = Policy_Count), alpha = .5, col = "blue") +
  geom_smooth(se = FALSE, col = "red") +
  facet_wrap(~ PSCD09) +
  scale_x_continuous(breaks = c(20, 30, 40, 50, 60, 70)) +
  labs(title = "ITD LR by Issue Age & Gender", x = "Issue Age", size = "Policy Count")
```

#####Comments


***

```{r ITD LR by Issue Age & Gender, echo=FALSE, message = FALSE}
LR_By_Issue_Age_Gender %>%
  filter(LR < 150, Policy_Count > 20) %>%
  ggplot(aes(x = PSNO13, y = LR, col = PSCD09)) +
  geom_line() +
  geom_point(aes(size = Policy_Count), alpha = .5) +
  geom_smooth(se = FALSE) +
  labs(title = "ITD LR by Issue Age & Gender", x = "Issue Age", size = "Policy Count", col = "Gender")
```

#####Comments

***

```{r ITD LR by Issue Age & Gender Facet, echo=FALSE, message = FALSE}
LR_By_Issue_Age_Gender %>%
  filter(LR < 150, Policy_Count > 20) %>%
  ggplot(aes(x = PSNO13, y = LR)) +
  geom_line(col = "blue") +
  geom_point(aes(size = Policy_Count), alpha = .5, col = "blue") +
  geom_smooth(se = FALSE, col = "red") +
  facet_wrap(~ PSCD09) +
  scale_x_continuous(breaks = c(20, 30, 40, 50, 60, 70)) +
  labs(title = "ITD LR by Issue Age & Gender", x = "Issue Age", size = "Policy Count")
```

#####Comments

***

```{r ITD LR by Issue Age & Gender, echo=FALSE, message = FALSE}
LR_By_Issue_Age_Gender %>%
  filter(LR < 150, Policy_Count > 20) %>%
  ggplot(aes(x = PSNO13, y = LR, col = PSCD09)) +
  geom_line() +
  geom_point(aes(size = Policy_Count), alpha = .5) +
  geom_smooth(se = FALSE) +
  labs(title = "ITD LR by Issue Age & Gender", x = "Issue Age", size = "Policy Count", col = "Gender")
```

#####Comments

***

```{r ITD LR by Issue Age & Gender Facet, echo=FALSE, message = FALSE}
LR_By_Issue_Age_Gender %>%
  filter(LR < 150, Policy_Count > 20) %>%
  ggplot(aes(x = PSNO13, y = LR)) +
  geom_line(col = "blue") +
  geom_point(aes(size = Policy_Count), alpha = .5, col = "blue") +
  geom_smooth(se = FALSE, col = "red") +
  facet_wrap(~ PSCD09) +
  scale_x_continuous(breaks = c(20, 30, 40, 50, 60, 70)) +
  labs(title = "ITD LR by Issue Age & Gender", x = "Issue Age", size = "Policy Count")
```

#####Comments

***

```{r ITD LR by Issue Age & Gender, echo=FALSE, message = FALSE}
LR_By_Issue_Age_Gender %>%
  filter(LR < 150, Policy_Count > 20) %>%
  ggplot(aes(x = PSNO13, y = LR, col = PSCD09)) +
  geom_line() +
  geom_point(aes(size = Policy_Count), alpha = .5) +
  geom_smooth(se = FALSE) +
  labs(title = "ITD LR by Issue Age & Gender", x = "Issue Age", size = "Policy Count", col = "Gender")
```

#####Comments

***

```{r ITD LR by Issue Age & Gender Facet, echo=FALSE, message = FALSE}
LR_By_Issue_Age_Gender %>%
  filter(LR < 150, Policy_Count > 20) %>%
  ggplot(aes(x = PSNO13, y = LR)) +
  geom_line(col = "blue") +
  geom_point(aes(size = Policy_Count), alpha = .5, col = "blue") +
  geom_smooth(se = FALSE, col = "red") +
  facet_wrap(~ PSCD09) +
  scale_x_continuous(breaks = c(20, 30, 40, 50, 60, 70)) +
  labs(title = "ITD LR by Issue Age & Gender", x = "Issue Age", size = "Policy Count")
```

#####Comments
----


```{r ITD LR by Issue Age & Gender Chart, echo = FALSE, results='asis',error=FALSE, warning=FALSE, include= FALSE}
## Remove the "include=FALSE" above once summary table is made

##creates custom CSS file in directory for color formatting etc.
writeLines("td, th { padding : 12px } th { background-color : grey ; color : white; border : 1px solid white; } td { color : black ; border : 1px solid grey }", con = "mystyle.css")

kable(LR_By_Issue_Age_Gender, format = "html")
```

##### Summary Table for LRxAgexGender
***
----

```{r ITD LR by ,echo=FALSE, error=FALSE, warning=FALSE}
ggplot(LR_By_Top_Agent, aes(x = AGTOPNAMEL, y = LR, size = Premiums_Sum)) +
  geom_point(col = "blue", alpha = .5) +
  theme(axis.text.x = element_text(angle = -30, vjust = 1, hjust = 0)) +
  labs(title = "ITD LR by Top Agent", x = "Top Agent", size = "Total Premiums") +
  scale_size_continuous(breaks = c(1000000, 2000000, 3000000, 5000000, 10000000, 15000000), 
                        labels = c("1m", "2m", "3m", "5m", "10m", "15m"))
```

#####Comments



----



#### LR By Gender
```{r LR By Gender Chart, echo=FALSE, results='asis', error=FALSE, warning=FALSE}


##creates custom CSS file in directory for color formatting etc.
writeLines("td, th { padding : 6px } th { background-color : grey ; color : white; border : 1px solid white; } td { color : black ; border : 1px solid grey }", con = "mystyle.css")

kable(LR_By_Gender, format = "html")
```


***

